[theme]
base = "dark"
primaryColor = "#FF6900"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#161616"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
