[theme]
base = "dark"
primaryColor = "#E93030"
backgroundColor = "#0F1219"
secondaryBackgroundColor = "#1A1E28"
textColor = "#F0F1F5"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = true
maxMessageSize = 500

[runner]
fastReruns = true
magicEnabled = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false
